### ISSUE TITLE
work in progress?

### ISSUE THREAD

**Issue by TestniTester** [gtklocker/bittrex-orderbook#4]
hi,
is this project in progress?
cos it dosent work for me

**Comment by dionyziz** [comment]
Yes, it's in progress. What doesn't work for you?

**Comment by TestniTester** [comment]
whell the code is not complete :D 
market.js line 14 ?

**Comment by gtklocker** [comment]
Please be specific about the issue you're having.

**Comment by dionyziz** [comment]
It works for me. What issue are you having?

**Comment by TestniTester** [comment]
/lib/market.js
line 14
...order
compile error?

**Comment by dionyziz** [comment]
No, this looks fine. Please use the latest version of node.js. Which version are you currently using?

**Comment by TestniTester** [comment]
6.11.4

**Comment by TestniTester** [comment]
if i run the example i get this
(node:6442) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Object.values is not                  a function

**Comment by TestniTester** [comment]
if i run example i get this=>
/node_modules/bittrex-orderbook/lib/market.js:14
                ...order
                ^^^

SyntaxError: Unexpected token ...

**Comment by dionyziz** [comment]
Try upgrading to node v9.1.0.

**Comment by gtklocker** [comment]
You don't have a version of Node that supports the current ES2017+ syntax.

Seeing that Node v6 is still LTS, I made some changes so that the packaged version is compatible with all Node versions. The fix has landed on `v2.0.5`. Thanks for reporting.
