### ISSUE TITLE
Detect disconnections

### ISSUE THREAD

**Issue by ghost** [gtklocker/bittrex-orderbook#8]
Hello,

How can I detect a disconnection of the websocket?

Is it only a single websocket for all streams or multiple websockets?

Thanks

**Comment by gtklocker** [comment]
One connection is used. The underlying library will try to reconnect in case of failure, but if you're not seeing data for a significant amount of time it may be a good idea to restart the manager. The behaviour long-lived connections is not guaranteed by Bittrex as this is an unofficial API. Feel free to comment further or open another more specific issue if you feel the need.
